### ISSUE TITLE
built-in ORM

### ISSUE THREAD

**Issue by aryaniyaps** [r4fek/django-cassandra-engine#147]
This is a great project and the only way to use cassandra with django right now. If not for this project, I wouldn't know what to do.
Thanks for maintaining this @r4fek !

I noticed that this uses the datastax orm, and not something native.
I was thinking whether I could contribute to making an ORM for cassandra.

Is this possible? Why hasn't this been done yet (any problems) ?
If so, please let me know, I am willing to contribute.

**Comment by r4fek** [comment]
Thank you @aryan340 for your kind words!

Cqlengine library (now part of cassandra-driver) serves this purpose. Why do you want to introduce similar ORM? What are potential gains? What do you mean by "something native"?

Looking forward to hearing from you!

**Comment by aryan340** [comment]
I meant something like an object document mapper for django. Django already has an orm which supports foreign keys and plays well with  relational databases.

Since this is the only library revolving around nosql and django that actually works, if we implement a document mapper for django, it would also serve as the stepping stone for other nosql backends for django.

This feature is not currently on the priority list for django itself,but could be a third party library.

**Comment by r4fek** [comment]
I think it would be hard because every noSQL database is different and has its own features and caveats. If you have a plan how to do it, I'm willing to help ;)
