### ISSUE TITLE
why should i use django-cassandra-engine over cassandra-drive?

### ISSUE THREAD

**Issue by vbrchn** [r4fek/django-cassandra-engine#54]
Based on issues raised on this forum and based on my experience, django admin module, user authentication doesn't work with django-cassandra-engine if cassandra is the only backend. May i know what are reasons for using django-cassandra-engine over cassandra-drive. sorry for the dumb question.

**Comment by r4fek** [comment]
Hi @vbrchn!

It's of course not a dumb question, I'll try to explain it to you. Basically Django ORM is created for relational databases and Cassandra is very specific noSQL database. It's nearly impossible to plug into Django ORM and execute efficient queries to Cassandra. Also modeling data for Cassandra is very different from we're all used to. That's why I decided to use cassandra-driver and Cqlengine as object mapper, which is maintained by DataStax, and very well documented.

This way you can use Django apps you're used to (auth, admin, contenttypes, etc.) along with apps dedicated to cassandra for better performance. Sometimes you don't need to use Django apps and then (and only then) use django-cassandra-engine as default (primary) database backend.

If you have further questions don't hesitate to ask.

**Comment by vbrchn** [comment]
Not working out for me without support for admin pages for models stored in cassandra. thanks for your help. I wish you all the best.
